### ISSUE TITLE
Please add English language to the Blocks command

### ISSUE THREAD

**Issue by narongporn** [MKleinSB/pxt-mpr121#2]
First of all, thanks for your contribution in development of this extension.
By the way, I cannot read German. I would like to ask for your time to add English language to the Blocks commands, so that this extension will be easy to use.

I also try the event "wenn Berührungssensor T11 berührt" and found that 
when I touch sensor T11 this event occurred twice from single touch.
The other sensor T0-T10 work fine.
Since I have only 1 touch pad, so I am not sure whether my hardware is the cause of this error.

Thanks

**Comment by philipphenkel** [comment]
@narongporn If you are using a micro:bit you could try the extension pxt-makerbit-touch (this extension is a fork). It's available in English by default.

https://github.com/1010Technologies/pxt-makerbit-touch

**Comment by narongporn** [comment]
Thanks for your advice.
